#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Jan 10 13:22:16 2020

@author: Jaakko Ahola, Finnish Meteorological Institute
@licence: MIT licence Copyright
"""
import os

class FileSystem:
    def createSubfolder(rootfolderName, subfolderName):
        subfolder = os.path.join( rootfolderName, subfolderName)
        if not os.path.exists( subfolder ):
            os.makedirs( subfolder )
        
        return subfolder
